### ISSUE TITLE
the $m doesn't work in IE

### ISSUE THREAD

**Issue by certik** [jaredly/PJs#1]
Hi,

this line fails in IE:

```
var match = (fn+'').match(fnrx);
if (!match)
    throw "ParseError: sorry, something went wrong on my end; are you sure you're passing me a valid function?" + (fn+'');
```

e.g. match is "null", I guess IE doesn't implement pattern matching. That's a deal breaker for me, as I need it to work in IE. Any ideas how to rewrite it so that it works in IE?

**Comment by jaredly** [comment]
Which version of IE are you working with?

**Comment by jaredly** [comment]
I've just fixed it to work (at least w/ IE 8). To check, try this test page: http://jabapyth.github.com/PJs/browser/jqueryui.html if you see it beautifully tabbed, then it's working. If you get a javascript error, then...it's not.

thanks

**Comment by certik** [comment]
I just checked and we have IE7 (and all the computers on campus have IE7, so I want to support it). Your test page works awesome in chrome, but not in IE7 (not tabs at all).

How can I debug the javascript in IE7? Maybe I can help to get it fixed, but the IE7 just tells me the line number 1298, but my script has only 300 lines, so I have not figured it out and I used alert() statements to get to the line that fails.

**Comment by jaredly** [comment]
haha! IE7 is vanquished. Check the example page now.

**Comment by certik** [comment]
Wow, indeed, it works! I have copied your whole pyjslib.js into our py-builtins.js, just removed your window.console code, as the window is not defined in spidermonkey, where we test our stuff locally (I guess it's trivial to fix). Here is some demo for you:

http://mattpap.github.com/py2js/html/static/examples/ui.html

and here is the source code:

http://github.com/mattpap/py2js/blob/master/examples/ui.py

I think that's really cool, as I wrap low level JS libraries like Ext and Canvas into Pythonic classes and then just use pure Python. It's the same spirit like Cython (if you use it) to wrap low level C/C++ into Pythonic classes.

**Comment by jaredly** [comment]
that looks sweet :) I fixed the "window" error btw
